version: '3'
services:
  web:
    container_name: mdf-vuejs
    image: mdf-frontend
    build:
      context: .
      dockerfile: ./docker/prod.docker
    volumes:
      - .:/var/www/docker-vue
      - /var/www/docker-vue/node_modules
    environment:
      - npm_config_unsafe_perm=true
    ports:
      - "80:80"